version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: npm run start
    environment:
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}

  graphql-backend:
    build:
      context: ./graphql-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    command: npm run start
    environment:
      - OTEL_SERVICE_NAME=graphql-backend
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io:443
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=${HONEYCOMB_API_KEY}
